### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by poschialex** [gembutterfly/sausagepan#10]

**Comment by limbusdev** [comment]
Ich brauche natürlich noch eure Credits, bevor ich welche eintragen kann ^^

**Comment by Sara-chi** [comment]
ich hab keine credits. hab nur die musik reingenommen die schon andere ins git gelegt hatten xD
(und bilder sind die von Alex oder selbstgemacht)

generell haben wir aber auch vorhin nochmal wegen der musik geredet. eigentlich könnte das auch noch etwas vereinheitlicht werden, also überall die gleiche musik...oder was meint die allgemeinheit?

**Comment by limbusdev** [comment]
Das wäre ein neuer Issue, der hier ist erledigt.
