### ISSUE TITLE
Spiel um Orange+Violett zu gewinnen

### ISSUE THREAD

**Issue by poschialex** [gembutterfly/sausagepan#5]

**Comment by poschialex** [comment]
Quiz fertig, Kristalle müssen noch übergeben werden

**Comment by limbusdev** [comment]
Da weiß ich leider nicht wie das im Spiel geschieht, das hat Sergej gemacht, oder? Wäre gut, wenn er da mal rein guckt.

**Comment by sergejSDA** [comment]
Einfach in der Itemdatabase den richtigen Kristall raussuchen (id) .... inventory suchen und die methode AddItem(id) aufrufen, und fertig :)

orange hat die id 2 und magenta 5

**Comment by limbusdev** [comment]
Vlt können wir uns das morgen mal gemeinsam ansehen.
